### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by bertsky** [Planet-AI-GmbH/tfaip#5]
The [docs](https://tfaip.readthedocs.io/en/latest/doc.installation.html?highlight=python#prerequisites) do mention explicitly that 3.7 or later is needed. But (considering this means Calamari won't install on 3.6 as well) I wonder whether and why this is necessary.

**Comment by ChWick** [comment]
`tfaip` uses several language features of python3.7, mainly related to the typing system and dataclasses. Since python 3.8 is the default version of Ubuntu 20.04 and python3.7 can easily be installed on older Ubuntu LTS versions, there should be - in most cases - no drawback.

**Comment by bertsky** [comment]
Agreed. Thanks for explaining! (Perhaps this dependency should also be mentioned for Calamari – if necessary differentiating between 1.x and 2.x ...)
