### ISSUE TITLE
Output of subprocesses held in buffer

### ISSUE THREAD

**Issue by andbue** [Planet-AI-GmbH/tfaip#7]
When running jobs on a kubernetes cluster (even if the main script is started with `python -u`), progress output of the Predictor is only shown after the whole dataset is finished, which is a bit confusing and made me cancel the process several times, thinking there was something wrong. I found some suggestions to call `sys.stdout.flush()` regularly to push the output of spawned processes through to the logs/terminals, but I'm not sure where exactly to put that in tfaip. Interestingly, this seems to be only the case during prediction but not while training. Have you got any idea what could be going on here?

**Comment by TobiasGruening** [comment]
Since the hopes we had for the release of the repo have not been fulfilled, we will freeze it at its current state, archive it and no longer maintain it in the open source variant.

I'm sorry if this leads to problems, but we have to direct our resources a little differently.
