### ISSUE TITLE
CUDA_VISIBLE_DEVICES="-1" not working as expected

### ISSUE THREAD

**Issue by andbue** [Planet-AI-GmbH/tfaip#8]
According to [Nvidia](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars), setting "-1" in CUDA_VISIBLE_DEVICES should disable all GPUs enumerated afterwards in that environment variable. When CUDA_VISIBLE_DEVICES is set to "-1", tfaip unfortunately fails with IndexError:
https://github.com/Planet-AI-GmbH/tfaip/blob/5d8c1fa5eb7271198ccb40f90ba10a7d53488764/tfaip/device/device_config.py#L94-L99
It would be great to implement the behaviour consistently with the Nvidia docs!

**Comment by TobiasGruening** [comment]
Since the hopes we had for the release of the repo have not been fulfilled, we will freeze it at its current state, archive it and no longer maintain it in the open source variant.

I'm sorry if this leads to problems, but we have to direct our resources a little differently.
